package io.github.rabinarayanpatra.enumx.processor;

import com.google.auto.service.AutoService;
import com.squareup.javapoet.*;
import io.github.rabinarayanpatra.enumx.annotations.*;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.ElementFilter;
import javax.tools.Diagnostic;
import java.io.IOException;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Annotation processor that generates Spring REST controllers for enums marked with @EnumApi.
 */
@AutoService(Processor.class)
@SupportedAnnotationTypes("io.github.rabinarayanpatra.enumx.annotations.EnumApi")
@SupportedSourceVersion(SourceVersion.RELEASE_21)
public class EnumxProcessor extends AbstractProcessor {

    private Messager messager;
    private Filer filer;

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        messager = processingEnv.getMessager();
        filer = processingEnv.getFiler();
    }

    @Override
    public SourceVersion getSupportedSourceVersion() {
        // Support latest version
        return SourceVersion.latest();
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        for (Element element : roundEnv.getElementsAnnotatedWith(EnumApi.class)) {
            if (element.getKind() != ElementKind.ENUM) {
                error(element, "@EnumApi can only be applied to enums");
                continue;
            }

            TypeElement enumElement = (TypeElement) element;
            try {
                generateController(enumElement);
            } catch (IOException e) {
                error(element, "Failed to generate controller: " + e.getMessage());
            }
        }
        return true;
    }

    private void generateController(TypeElement enumElement) throws IOException {
        EnumApi enumApi = enumElement.getAnnotation(EnumApi.class);
        String packageName = getPackageName(enumElement);
        String enumSimpleName = enumElement.getSimpleName().toString();
        String controllerName = enumSimpleName + "Controller";

        List<ExposedField> exposedFields = getExposedFields(enumElement, enumApi);
        List<FilterableField> filterableFields = getFilterableFields(enumElement);

        TypeSpec controller = TypeSpec.classBuilder(controllerName)
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "RestController"))
                .addAnnotation(AnnotationSpec.builder(ClassName.get("org.springframework.web.bind.annotation", "RequestMapping"))
                        .addMember("value", "$S", "/api/" + enumApi.path())
                        .build())
                .addField(createEnumArrayField(enumElement))
                .addMethod(createGetAllMethod(enumElement, enumApi, exposedFields))
                .addMethod(createValidateMethod(enumElement))
                .addMethod(createMatchesFiltersMethod(enumElement, filterableFields))
                .addMethod(createValidateFiltersMethod(filterableFields))
                .build();

        JavaFile javaFile = JavaFile.builder(packageName + ".generated", controller)
                .addFileComment("Generated by EnumX - Do not modify")
                .build();

        javaFile.writeTo(filer);

        messager.printMessage(Diagnostic.Kind.NOTE,
                "Generated controller: " + packageName + ".generated." + controllerName);
    }

    private FieldSpec createEnumArrayField(TypeElement enumElement) {
        ClassName enumClassName = ClassName.get(enumElement);
        return FieldSpec.builder(ArrayTypeName.of(enumClassName), "VALUES")
                .addModifiers(Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                .initializer("$T.values()", enumClassName)
                .build();
    }

    private MethodSpec createGetAllMethod(TypeElement enumElement, EnumApi enumApi, List<ExposedField> exposedFields) {
        ClassName enumClassName = ClassName.get(enumElement);
        ParameterizedTypeName returnType = ParameterizedTypeName.get(
                ClassName.get(List.class),
                ParameterizedTypeName.get(ClassName.get(Map.class),
                        ClassName.get(String.class), ClassName.get(Object.class))
        );

        MethodSpec.Builder method = MethodSpec.methodBuilder("getAll")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "GetMapping"))
                .addParameter(ParameterSpec.builder(
                                ParameterizedTypeName.get(Map.class, String.class, String.class), "filters")
                        .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "RequestParam"))
                        .build())
                .returns(returnType);

        method.addStatement("$T<String, String> queryFilters = filters == null ? new $T<>() : new $T<>(filters)",
                Map.class, LinkedHashMap.class, LinkedHashMap.class);
        method.addStatement("validateFilters(queryFilters)");
        method.addStatement("$T<$T<String, Object>> result = new $T<>()",
                List.class, Map.class, ArrayList.class);

        method.beginControlFlow("for ($T value : VALUES)", enumClassName);
        method.beginControlFlow("if (!matchesFilters(value, queryFilters))");
        method.addStatement("continue");
        method.endControlFlow();

        method.addStatement("$T<String, Object> item = new $T<>()", Map.class, LinkedHashMap.class);
        method.addStatement("item.put($S, value.name())", enumApi.keyField());

        for (ExposedField field : exposedFields) {
            method.addStatement("item.put($S, value.$L())", field.apiName(), field.getterName());
        }

        method.addStatement("result.add(item)");
        method.endControlFlow();
        method.addStatement("return result");

        return method.build();
    }

    private MethodSpec createValidateMethod(TypeElement enumElement) {
        ClassName enumClassName = ClassName.get(enumElement);
        ParameterizedTypeName returnType = ParameterizedTypeName.get(
                ClassName.get(Map.class),
                ClassName.get(String.class),
                ParameterizedTypeName.get(ClassName.get(List.class), ClassName.get(String.class))
        );

        return MethodSpec.methodBuilder("validate")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(AnnotationSpec.builder(
                                ClassName.get("org.springframework.web.bind.annotation", "PostMapping"))
                        .addMember("value", "$S", "/validate")
                        .build())
                .addParameter(ParameterSpec.builder(
                                ParameterizedTypeName.get(List.class, String.class), "values")
                        .addAnnotation(ClassName.get("org.springframework.web.bind.annotation", "RequestBody"))
                        .build())
                .returns(returnType)
                .addStatement("$T<String> valid = new $T<>()", List.class, ArrayList.class)
                .addStatement("$T<String> invalid = new $T<>()", List.class, ArrayList.class)
                .addStatement("$T<String> enumNames = $T.stream(VALUES).map($T::name).collect($T.toSet())",
                        Set.class, Arrays.class, enumClassName, Collectors.class)
                .beginControlFlow("for (String value : values)")
                .beginControlFlow("if (enumNames.contains(value))")
                .addStatement("valid.add(value)")
                .nextControlFlow("else")
                .addStatement("invalid.add(value)")
                .endControlFlow()
                .endControlFlow()
                .addStatement("$T<String, $T<String>> result = new $T<>()",
                        Map.class, List.class, HashMap.class)
                .addStatement("result.put($S, valid)", "valid")
                .addStatement("result.put($S, invalid)", "invalid")
                .addStatement("return result")
                .build();
    }

    private MethodSpec createValidateFiltersMethod(List<FilterableField> filterableFields) {
        ClassName responseStatusException = ClassName.get("org.springframework.web.server", "ResponseStatusException");
        ClassName httpStatus = ClassName.get("org.springframework.http", "HttpStatus");

        MethodSpec.Builder method = MethodSpec.methodBuilder("validateFilters")
                .addModifiers(Modifier.PRIVATE)
                .addParameter(ParameterizedTypeName.get(Map.class, String.class, String.class), "filters");

        method.beginControlFlow("if (filters == null || filters.isEmpty())")
                .addStatement("return")
                .endControlFlow();

        if (filterableFields.isEmpty()) {
            method.addStatement("throw new $T($T.BAD_REQUEST, $S)",
                    responseStatusException, httpStatus, "Filtering is not supported for this enum");
            return method.build();
        }

        CodeBlock.Builder allowed = CodeBlock.builder();
        for (int i = 0; i < filterableFields.size(); i++) {
            if (i > 0) {
                allowed.add(", ");
            }
            allowed.add("$S", filterableFields.get(i).filterName());
        }

        method.addStatement("$T<String> allowedFilters = $T.of($L)", Set.class, Set.class, allowed.build());

        ParameterizedTypeName entryType = ParameterizedTypeName.get(ClassName.get(Map.Entry.class),
                ClassName.get(String.class), ClassName.get(String.class));

        method.beginControlFlow("for ($T entry : filters.entrySet())", entryType)
                .addStatement("String filterName = entry.getKey()")
                .beginControlFlow("if (filterName == null || filterName.isBlank())")
                .addStatement("throw new $T($T.BAD_REQUEST, $S)",
                        responseStatusException, httpStatus, "Filter name must not be blank")
                .endControlFlow()
                .beginControlFlow("if (!allowedFilters.contains(filterName))")
                .addStatement("throw new $T($T.BAD_REQUEST, \"Unknown filter '\" + filterName + \"'\")",
                        responseStatusException, httpStatus)
                .endControlFlow()
                .addStatement("String filterValue = entry.getValue()")
                .beginControlFlow("if (filterValue == null)")
                .addStatement("throw new $T($T.BAD_REQUEST, \"Filter '\" + filterName + \"' must include a value\")",
                        responseStatusException, httpStatus)
                .endControlFlow()
                .addStatement("String trimmed = filterValue.trim()")
                .beginControlFlow("if (trimmed.isEmpty())")
                .addStatement("throw new $T($T.BAD_REQUEST, \"Filter '\" + filterName + \"' must include a value\")",
                        responseStatusException, httpStatus)
                .endControlFlow()
                .addStatement("entry.setValue(trimmed)")
                .endControlFlow();

        return method.build();
    }

    private MethodSpec createMatchesFiltersMethod(TypeElement enumElement, List<FilterableField> filterableFields) {
        ClassName enumClassName = ClassName.get(enumElement);

        MethodSpec.Builder method = MethodSpec.methodBuilder("matchesFilters")
                .addModifiers(Modifier.PRIVATE)
                .addParameter(enumClassName, "value")
                .addParameter(ParameterizedTypeName.get(Map.class, String.class, String.class), "filters")
                .returns(boolean.class)
                .beginControlFlow("if (filters == null || filters.isEmpty())")
                .addStatement("return true")
                .endControlFlow();

        if (filterableFields.isEmpty()) {
            method.addStatement("return filters.isEmpty()");
            return method.build();
        }

        ParameterizedTypeName entryType = ParameterizedTypeName.get(ClassName.get(Map.Entry.class),
                ClassName.get(String.class), ClassName.get(String.class));

        method.beginControlFlow("for ($T entry : filters.entrySet())", entryType);
        method.addStatement("String filterName = entry.getKey()");
        method.addStatement("String filterValue = entry.getValue()");
        method.beginControlFlow("if (filterName == null)");
        method.addStatement("continue");
        method.endControlFlow();
        method.beginControlFlow("if (filterValue == null)");
        method.addStatement("return false");
        method.endControlFlow();
        method.beginControlFlow("switch (filterName)");

        for (FilterableField field : filterableFields) {
            method.addCode(buildFilterCase(field));
        }

        method.addCode("default -> { return false; }\n");
        method.endControlFlow();
        method.endControlFlow();
        method.addStatement("return true");

        return method.build();
    }

    private List<ExposedField> getExposedFields(TypeElement enumElement, EnumApi enumApi) {
        List<ExposedField> exposedFields = new ArrayList<>();
        Set<String> seenApiNames = new HashSet<>();

        for (VariableElement field : ElementFilter.fieldsIn(enumElement.getEnclosedElements())) {
            if (!isProcessableField(field)) {
                continue;
            }

            if (field.getAnnotation(Hide.class) != null) {
                continue;
            }

            boolean explicitlyExposed = field.getAnnotation(Expose.class) != null
                    || field.getAnnotation(Filterable.class) != null;
            if (!explicitlyExposed && !enumApi.includeAllFields()) {
                continue;
            }

            Optional<String> getterName = findGetterName(enumElement, field);
            if (getterName.isEmpty()) {
                error(field, String.format(
                        "Field '%s' must declare an accessible getter (one of %s) to be exposed",
                        field.getSimpleName(), getterCandidates(field)));
                continue;
            }

            String apiName = getApiName(field);
            if (!seenApiNames.add(apiName)) {
                error(field, "Duplicate API field name '" + apiName + "' detected. Use @Expose to disambiguate.");
                continue;
            }

            exposedFields.add(new ExposedField(apiName, getterName.get()));
        }

        return exposedFields;
    }

    private List<FilterableField> getFilterableFields(TypeElement enumElement) {
        List<FilterableField> filterableFields = new ArrayList<>();
        Set<String> seenFilterNames = new HashSet<>();

        for (VariableElement field : ElementFilter.fieldsIn(enumElement.getEnclosedElements())) {
            if (!isProcessableField(field)) {
                continue;
            }

            Filterable filterable = field.getAnnotation(Filterable.class);
            if (filterable == null) {
                continue;
            }

            Optional<String> getterName = findGetterName(enumElement, field);
            if (getterName.isEmpty()) {
                error(field, String.format(
                        "Field '%s' marked with @Filterable requires an accessible getter (one of %s)",
                        field.getSimpleName(), getterCandidates(field)));
                continue;
            }

            String filterName = filterable.value().isEmpty() ? getApiName(field) : filterable.value();
            if (!seenFilterNames.add(filterName)) {
                error(field, "Duplicate filter name '" + filterName + "' detected. Choose unique @Filterable values.");
                continue;
            }

            TypeName typeName = TypeName.get(field.asType());
            FilterFieldType fieldType = resolveFilterFieldType(field.asType());
            filterableFields.add(new FilterableField(
                    filterName,
                    getterName.get(),
                    field.asType(),
                    typeName,
                    fieldType,
                    !typeName.isPrimitive()
            ));
        }

        return filterableFields;
    }

    private boolean isProcessableField(VariableElement field) {
        if (field.getModifiers().contains(Modifier.STATIC)) {
            return false;
        }
        String fieldName = field.getSimpleName().toString();
        return !fieldName.startsWith("$");
    }

    private Optional<String> findGetterName(TypeElement enumElement, VariableElement field) {
        for (String candidate : getterCandidates(field)) {
            if (hasMethod(enumElement, candidate)) {
                return Optional.of(candidate);
            }
        }
        return Optional.empty();
    }

    private List<String> getterCandidates(VariableElement field) {
        String fieldName = field.getSimpleName().toString();
        String capitalizedName = Character.toUpperCase(fieldName.charAt(0)) + fieldName.substring(1);
        List<String> candidates = new ArrayList<>();

        if (isBooleanType(field.asType())) {
            if (fieldName.startsWith("is") && fieldName.length() > 2 &&
                    Character.isUpperCase(fieldName.charAt(2))) {
                candidates.add(fieldName);
            }
            candidates.add("is" + capitalizedName);
        }
        candidates.add("get" + capitalizedName);

        return candidates;
    }

    private boolean isBooleanType(TypeMirror typeMirror) {
        return typeMirror.getKind() == TypeKind.BOOLEAN ||
                Objects.equals(typeMirror.toString(), Boolean.class.getCanonicalName());
    }

    private String getApiName(VariableElement field) {
        Expose expose = field.getAnnotation(Expose.class);
        if (expose != null && !expose.value().isEmpty()) {
            return expose.value();
        }
        return field.getSimpleName().toString();
    }

    private FilterFieldType resolveFilterFieldType(TypeMirror typeMirror) {
        TypeKind kind = typeMirror.getKind();
        return switch (kind) {
            case BOOLEAN -> FilterFieldType.BOOLEAN;
            case BYTE -> FilterFieldType.BYTE;
            case SHORT -> FilterFieldType.SHORT;
            case INT -> FilterFieldType.INT;
            case LONG -> FilterFieldType.LONG;
            case FLOAT -> FilterFieldType.FLOAT;
            case DOUBLE -> FilterFieldType.DOUBLE;
            case DECLARED -> resolveDeclaredFilterType(typeMirror);
            default -> FilterFieldType.UNKNOWN;
        };
    }

    private FilterFieldType resolveDeclaredFilterType(TypeMirror typeMirror) {
        String typeName = typeMirror.toString();
        return switch (typeName) {
            case "java.lang.String" -> FilterFieldType.STRING;
            case "java.lang.Boolean" -> FilterFieldType.BOOLEAN;
            case "java.lang.Byte" -> FilterFieldType.BYTE;
            case "java.lang.Short" -> FilterFieldType.SHORT;
            case "java.lang.Integer" -> FilterFieldType.INT;
            case "java.lang.Long" -> FilterFieldType.LONG;
            case "java.lang.Float" -> FilterFieldType.FLOAT;
            case "java.lang.Double" -> FilterFieldType.DOUBLE;
            case "java.math.BigDecimal" -> FilterFieldType.BIG_DECIMAL;
            case "java.math.BigInteger" -> FilterFieldType.BIG_INTEGER;
            default -> isEnum(typeMirror) ? FilterFieldType.ENUM : FilterFieldType.UNKNOWN;
        };
    }

    private boolean isEnum(TypeMirror typeMirror) {
        if (!(typeMirror instanceof DeclaredType declaredType)) {
            return false;
        }
        Element element = declaredType.asElement();
        return element != null && element.getKind() == ElementKind.ENUM;
    }

    private CodeBlock buildFilterCase(FilterableField field) {
        CodeBlock.Builder code = CodeBlock.builder();
        code.add("case $S -> {\n", field.filterName());
        code.indent();

        switch (field.fieldType()) {
            case STRING -> {
                code.addStatement("$T actual = value.$L()", field.typeName(), field.getterName());
                if (field.nullable()) {
                    code.addStatement("if (actual == null) return false");
                }
                code.addStatement("if (!java.util.Objects.equals(actual, filterValue)) return false");
            }
            case BOOLEAN -> {
                code.addStatement("$T actual = value.$L()", field.typeName(), field.getterName());
                if (field.nullable()) {
                    code.addStatement("if (actual == null) return false");
                }
                code.addStatement("boolean parsed = $T.parseBoolean(filterValue)", Boolean.class);
                code.addStatement("if (actual != parsed) return false");
            }
            case BYTE, SHORT, INT, LONG, FLOAT, DOUBLE -> {
                NumericStrategy strategy = numericStrategyFor(field.fieldType());
                addNumericCase(code, field, strategy);
            }
            case BIG_DECIMAL -> {
                code.addStatement("$T actual = value.$L()", field.typeName(), field.getterName());
                code.addStatement("if (actual == null) return false");
                code.addStatement("$T parsed", java.math.BigDecimal.class);
                code.add("try {\n");
                code.indent();
                code.addStatement("parsed = new $T(filterValue)", java.math.BigDecimal.class);
                code.unindent();
                code.add("} catch ($T ex) {\n", NumberFormatException.class);
                code.indent();
                code.addStatement("return false");
                code.unindent();
                code.add("}\n");
                code.addStatement("if (actual.compareTo(parsed) != 0) return false");
            }
            case BIG_INTEGER -> {
                code.addStatement("$T actual = value.$L()", field.typeName(), field.getterName());
                code.addStatement("if (actual == null) return false");
                code.addStatement("$T parsed", java.math.BigInteger.class);
                code.add("try {\n");
                code.indent();
                code.addStatement("parsed = new $T(filterValue)", java.math.BigInteger.class);
                code.unindent();
                code.add("} catch ($T ex) {\n", NumberFormatException.class);
                code.indent();
                code.addStatement("return false");
                code.unindent();
                code.add("}\n");
                code.addStatement("if (actual.compareTo(parsed) != 0) return false");
            }
            case ENUM -> {
                code.addStatement("$T actual = value.$L()", field.typeName(), field.getterName());
                code.addStatement("if (actual == null) return false");
                code.addStatement("$T parsed", field.typeName());
                code.add("try {\n");
                code.indent();
                code.addStatement("parsed = $T.valueOf(filterValue)", field.typeName());
                code.unindent();
                code.add("} catch ($T ex) {\n", IllegalArgumentException.class);
                code.indent();
                code.addStatement("return false");
                code.unindent();
                code.add("}\n");
                code.addStatement("if (actual != parsed) return false");
            }
            case UNKNOWN -> {
                code.addStatement("$T actual = value.$L()", field.typeName(), field.getterName());
                if (field.nullable()) {
                    code.addStatement("if (actual == null) return false");
                }
                code.addStatement("if (!java.util.Objects.equals(String.valueOf(actual), filterValue)) return false");
            }
        }

        code.unindent();
        code.add("}\n");
        return code.build();
    }

    private NumericStrategy numericStrategyFor(FilterFieldType fieldType) {
        return switch (fieldType) {
            case BYTE -> new NumericStrategy(Byte.class, "parseByte", "byte", null);
            case SHORT -> new NumericStrategy(Short.class, "parseShort", "short", null);
            case INT -> new NumericStrategy(Integer.class, "parseInt", "int", null);
            case LONG -> new NumericStrategy(Long.class, "parseLong", "long", null);
            case FLOAT -> new NumericStrategy(Float.class, "parseFloat", "float", Float.class);
            case DOUBLE -> new NumericStrategy(Double.class, "parseDouble", "double", Double.class);
            default -> throw new IllegalArgumentException("Unsupported numeric type: " + fieldType);
        };
    }

    private void addNumericCase(CodeBlock.Builder code, FilterableField field, NumericStrategy strategy) {
        code.addStatement("$T actual = value.$L()", field.typeName(), field.getterName());
        if (field.nullable()) {
            code.addStatement("if (actual == null) return false");
        }
        code.addStatement("$L parsed", strategy.primitiveType());
        code.add("try {\n");
        code.indent();
        code.addStatement("parsed = $T.$L(filterValue)", ClassName.get(strategy.parserClass()), strategy.methodName());
        code.unindent();
        code.add("} catch ($T ex) {\n", NumberFormatException.class);
        code.indent();
        code.addStatement("return false");
        code.unindent();
        code.add("}\n");
        if (strategy.comparatorClass() != null) {
            code.addStatement("if ($T.compare(actual, parsed) != 0) return false", ClassName.get(strategy.comparatorClass()));
        } else {
            code.addStatement("if (actual != parsed) return false");
        }
    }

    private String getPackageName(TypeElement element) {
        return processingEnv.getElementUtils().getPackageOf(element).toString();
    }

    private void error(Element element, String message) {
        messager.printMessage(Diagnostic.Kind.ERROR, message, element);
    }

    private boolean hasMethod(TypeElement type, String methodName) {
        for (ExecutableElement method : ElementFilter.methodsIn(type.getEnclosedElements())) {
            if (method.getSimpleName().contentEquals(methodName) && method.getParameters().isEmpty()) {
                return true;
            }
        }
        return false;
    }

    private enum FilterFieldType {
        STRING,
        BOOLEAN,
        BYTE,
        SHORT,
        INT,
        LONG,
        FLOAT,
        DOUBLE,
        BIG_DECIMAL,
        BIG_INTEGER,
        ENUM,
        UNKNOWN
    }

    private record ExposedField(String apiName, String getterName) {
    }

    private record FilterableField(String filterName,
                                   String getterName,
                                   TypeMirror typeMirror,
                                   TypeName typeName,
                                   FilterFieldType fieldType,
                                   boolean nullable) {
    }

    private record NumericStrategy(Class<?> parserClass,
                                   String methodName,
                                   String primitiveType,
                                   Class<?> comparatorClass) {
    }
}
